services:
  - type: web
    name: ai-study-companion
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production